version: '3.9'
services:
  app:
    image: this-is/your-image-name
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    # extra_hosts:
    #    - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:8080'
    environment:
      WWWUSER: '${WWWUSER}'
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: '1'
    volumes:
      - '.:/app'
    networks:
      - yournetwork

networks:
  yournetwork:
